spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
  application:
    name: catalog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081