spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/orders
        username: root
        password: 123
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: 'true'
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: localhost
        username: guest
        password: guest
        port: 5672
        virtual-host: /

server:
    port: 8080