server:
  port: 8090
spring:
  application:
    name: gateway-service
auth-service:
  base:
    url: http://localhost:8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
