server:
  port: 8090
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: CATALOG-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/items/**
