spring:
    jdbc:
        url: r2dbc:postgresql://127.0.0.1:5432/orders
        username: root
        password: 123
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: 'true'
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect