spring:
    r2dbc:
        url: r2dbc:postgresql://172.17.0.2:5432/postgres?schema=orders
        username: root
        password: test
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: 'true'
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect