services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "orders"
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "root"
    networks:
      - ecommerce-microservices
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql